version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mattilda
      POSTGRES_USER: mattilda
      POSTGRES_PASSWORD: mattilda
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mattilda -d mattilda"]
      interval: 3s
      timeout: 3s
      retries: 20

  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://mattilda:mattilda@db:5432/mattilda
      JWT_SECRET: change_me
      JWT_ALGORITHM: HS256
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
